services:
  postgres:
    image: postgres:17
    container_name: backstage_postgres
    restart: unless-stopped
    env_file: ../.env
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - backstage-net

  backstage:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: backstage_app
    command: ["node", "packages/backend", "--config", "app-config.yaml", "--config", "app-config.production.yaml"]
    restart: unless-stopped
    env_file: ../.env
    environment:
      - LOG_LEVEL=warn
    volumes:
      - ../app-config.production.yaml:/app/app-config.production.yaml
      - ../examples:/app/examples
    ports:
      - "7007:7007"
    depends_on:
      - postgres
    networks:
      - backstage-net

networks:
  backstage-net:
    driver: bridge