apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: backstage
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: backstage
  namespace: default