---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: hozalex
spec:
  memberOf: [admins, developers]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admins
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: developers
spec:
  type: team
  children: []
