apiVersion: v1
kind: Service
metadata:
  name: ${{ values.serviceName }}
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.serviceName }}
    backstage.io/kubernetes-id: ${{ values.serviceName }}
spec:
  selector:
    app: ${{ values.serviceName }}
  ports:
    - name: http
      protocol: TCP
      port: ${{ values.port }}
      targetPort: ${{ values.port }}
  type: ClusterIP
